name: Merge into Master
on:
  push:
    branches:
      - staging

jobs:
  merge-into-master:
    runs-on: ubuntu-latest
    steps:
      - name: update master branch
        run: |
          git init
          git remote add origin https://x-access-token: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@github.com/$GITHUB_REPOSITORY.git
          git pull origin master
          git pull origin staging --rebase
          git push origin master
