name: Merge into Master
on:
  push:
    branches:
      - staging

jobs:
  merge-into-master:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'
          token: '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'
      - name: merge staging into master
        run: |
          git pull origin staging --rebase
          git push origin master
